### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by tkakantousis** [volumeint/helium-volume-leaflet#3]
Hi everyone,

I'm using Zeppelin-0.8-SNAPSHOT and while trying to install the module, I got the following error:
```
./~/leaflet/dist/images/marker-icon.png
Module parse failed: /srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/leaflet/dist/images/marker-icon.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
at Parser.pp$4.raise (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/acorn/dist/acorn.js:2221:15)
at Parser.pp$7.getTokenFromCode (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/acorn/dist/acorn.js:2756:10)
at Parser.pp$7.readToken (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/acorn/dist/acorn.js:2477:17)
at Parser.pp$7.nextToken (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/acorn/dist/acorn.js:2468:15)
at Parser.parse (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/acorn/dist/acorn.js:515:10)
at Object.parse (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/acorn/dist/acorn.js:3098:39)
at Parser.parse (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/webpack/lib/Parser.js:902:15)
at DependenciesBlock. (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/webpack/lib/NormalModule.js:104:16)
at DependenciesBlock.onModuleBuild (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
at nextLoader (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
at /srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
at Storage.finished (/srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
at /srv/hops/zeppelin-0.8.0-SNAPSHOT/Projects/workshop/local-repo/helium-bundle/bundles/volume-leaflet/node_modules/graceful-fs/graceful-fs.js:78:16
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
@ ./index.js 25:18-64
```

any ideas? Thanks!

**Comment by volumeint** [comment]
Try a newer 0.8.0-SNAPSHOT.  The pull request that enabled this helium module was merged on May 6th, 2017.  https://github.com/apache/zeppelin/pull/2313.
